# Example: Home Assistant configuration for Tailscale devices
# Add this to your Home Assistant configuration.yaml

# REST sensor for Tailscale devices
rest:
  - resource: "http://tailscale-token-manager:1180/devices"
    name: "tailscale_devices"
    scan_interval: 300  # 5 minutes
    json_attributes_path: "$.devices"
    json_attributes:
      - "devices"
    value_template: "{{ value_json.devices | length }}"
    headers:
      Content-Type: "application/json"

# Template sensors for device statistics
template:
  - sensor:
      - name: "Tailscale Online Devices"
        state: >
          {% set devices = state_attr('sensor.tailscale_devices', 'devices') %}
          {% if devices %}
            {{ devices | selectattr('lastSeen', 'match', '.*online.*') | list | length }}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: "devices"
        icon: "mdi:vpn"

      - name: "Tailscale Offline Devices"
        state: >
          {% set devices = state_attr('sensor.tailscale_devices', 'devices') %}
          {% if devices %}
            {{ devices | rejectattr('lastSeen', 'match', '.*online.*') | list | length }}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: "devices"
        icon: "mdi:vpn-outline"

# Binary sensors for specific devices
binary_sensor:
  - platform: template
    sensors:
      my_phone_tailscale:
        friendly_name: "My Phone (Tailscale)"
        device_class: connectivity
        value_template: >
          {% set devices = state_attr('sensor.tailscale_devices', 'devices') %}
          {% if devices %}
            {% for device in devices %}
              {% if device.name == 'my-phone' %}
                {{ 'online' in device.lastSeen }}
              {% endif %}
            {% endfor %}
          {% else %}
            false
          {% endif %}

# Automation example
automation:
  - alias: "Device Connected to Tailscale"
    trigger:
      - platform: state
        entity_id: sensor.tailscale_online_devices
    condition:
      - condition: numeric_state
        entity_id: sensor.tailscale_online_devices
        above: 0
    action:
      - service: notify.mobile_app
        data:
          message: "{{ trigger.to_state.state }} devices are now connected to Tailscale"
          title: "Tailscale Network Status"